#### Center on Reinventing Public Education #### 
# Title: Change Columns (Script)
# Description: Rename the CCD Financial Dataset for the Database
# Created by: Kevin Cha on 08-02-17
# Updated by: Kevin Cha on 08-09-17
# Link to Github: https://github.com/CRPE-UWB/Federal

# renames the column
rename_col <- function(df) {
  names(df)[names(df) == "LEAID"] <- "LEAID" 
  names(df)[names(df) == "FIPST"] <- "FIPST" 
  names(df)[names(df) == "NAME"] <- "NAME"
  names(df)[names(df) == "YEAR"] <- "YEAR"
  names(df)[names(df) == "V33"] <- "FALL_MEMBERSHIP"
  names(df)[names(df) == "TOTALREV"] <- "REV_TOTAL"
  names(df)[names(df) == "TFEDREV"] <- "FEDREV_TOTAL"
  names(df)[names(df) == "C14"] <- "FEDREV_STATE_TITLEI"
  names(df)[names(df) == "C15"] <- "FEDREV_STATE_IDEA"
  names(df)[names(df) == "C16"] <- "FEDREV_STATE_MATHSCIENCE.TEACHERQUALITY"
  names(df)[names(df) == "C17"] <- "FEDREV_STATE_SAFE.DRUGFREE"
  names(df)[names(df) == "C19"] <- "FEDREV_STATE_VOCATIONAL.TECHED"
  names(df)[names(df) == "B11"] <- "FEDREV_STATE_BILINGUALED"
  names(df)[names(df) == "C20"] <- "FEDREV_STATE_OTHER"
  names(df)[names(df) == "C25"] <- "FEDREV_STATE_CHILDNUTRITIONACT"
  names(df)[names(df) == "C36"] <- "FEDREV_NONSPECIFIED"
  names(df)[names(df) == "B10"] <- "FEDREV_DIRECT_IMPACTAID"
  names(df)[names(df) == "B12"] <- "FEDREV_DIRECT_INDIANED"
  names(df)[names(df) == "B13"] <- "FEDREV_DIRECT_OTHERTOTALSTATEREV"
  names(df)[names(df) == "TSTREV"] <- "STATEREV_TOTAL"
  names(df)[names(df) == "C01"] <- "STATEREV_GENFORMULA.ASSISTANCE"
  names(df)[names(df) == "C04"] <- "STATEREV_STAFFIMPROV_PROGRAMS"
  names(df)[names(df) == "C05"] <- "STATEREV_SPED_PROGRAMS"
  names(df)[names(df) == "C06"] <- "STATEREV_COMPENSATORY.BASIC.SKILLSPROGRAM"
  names(df)[names(df) == "C07"] <- "STATEREV_BILINGUALED"
  names(df)[names(df) == "C08"] <- "STATEREV_GIFTED.TALENTED_PROGRAMS"
  names(df)[names(df) == "C09"] <- "STATEREV_VOCATIONALED_PROGRAMS"
  names(df)[names(df) == "C10"] <- "STATEREV_SCHOOLLUNCH"
  names(df)[names(df) == "C11"] <- "STATEREV_CAPITALOUTLAY.DEBTSERVICES"
  names(df)[names(df) == "C12"] <- "STATEREV_TRANSPORTATION"
  names(df)[names(df) == "C13"] <- "STATEREV_OTHER"
  names(df)[names(df) == "C35"] <- "STATEREV_NONSPECIFIED"
  names(df)[names(df) == "C38"] <- "STATEREV_ONBEHALF_EMPLOYEE.BENEFITS"
  names(df)[names(df) == "C39"] <- "STATEREV_ONBEHALF_NOTEMPLOYEE.BENEFITS"
  names(df)[names(df) == "TLOCREV"] <- "LOCALREV_TOTAL"
  names(df)[names(df) == "T02"] <- "LOCALREV_PARENTGOVCONRIBUTIONS"
  names(df)[names(df) == "T06"] <- "LOCALREV_PROPERTY_TAXES"
  names(df)[names(df) == "T09"] <- "LOCALREV_GENERALSALES_TAXES"
  names(df)[names(df) == "T15"] <- "LOCALREV_PUBLICUTILITY_TAXES"
  names(df)[names(df) == "T40"] <- "LOCALREV_INDIVIDUAL.CORPORATEINCOME_TAXES"
  names(df)[names(df) == "T99"] <- "LOCALREV_ALLOTHER_TAXES"
  names(df)[names(df) == "D11"] <- "LOCALREV_FROMOTHERSCHOOLSYSTEMS"
  names(df)[names(df) == "D23"] <- "LOCALREV_FROMCITIES.COUNTIES"
  names(df)[names(df) == "A07"] <- "LOCALREV_TUITIONFEESFROMPUPILS.PARENTS"
  names(df)[names(df) == "A08"] <- "LOCALREV_TRANSPORTATIONFEESFROMPUPILS.PARENTS"
  names(df)[names(df) == "A09"] <- "LOCALREV_SCHOOLLUNCH"
  names(df)[names(df) == "A11"] <- "LOCALREV_TEXTBOXSALES.RENTALS"
  names(df)[names(df) == "A13"] <- "LOCALREV_DISTRICTACTIVITY.RECEIPTS"
  names(df)[names(df) == "A15"] <- "LOCALREV_STUDENTFEES.NONSPECIFIED"
  names(df)[names(df) == "A20"] <- "LOCALREV_OTEHRSALES.SERVICES"
  names(df)[names(df) == "A40"] <- "LOCALREV_RENTS.ROYALTIES"
  names(df)[names(df) == "U11"] <- "LOCALREV_SALEOFPROPERTY"
  names(df)[names(df) == "U22"] <- "LOCALREV_INTERESTEARNINGS"
  names(df)[names(df) == "U30"] <- "LOCALREV_FINES.FORFEITS"
  names(df)[names(df) == "U50"] <- "LOCALREV_PRIVATECONTRIBUTIONS"
  names(df)[names(df) == "U97"] <- "LOCALREV_MISC"
  names(df)[names(df) == "C24"] <- "LOCALREV_NCES_CENSUSBUREAUSTATEREV"
  names(df)[names(df) == "TOTALEXP"] <- "CURRENTEXPEND_TOTAL"
  names(df)[names(df) == "TCURELSC"] <- "CURRENTEXPEND_ELEMSECONDEXPEND_TOTAL"
  names(df)[names(df) == "TCURINST"] <- "CURRENTEXPEND_INSTRUCTION_TOTAL"
  names(df)[names(df) == "E13"] <- "CURRENTEXPEND_INSTRUCTION"
  names(df)[names(df) == "V91"] <- "PAYMENTS_TOPRIVATESCH"
  names(df)[names(df) == "V92"] <- "PAYMENTS_TOCHARTERSCH"
  names(df)[names(df) == "TCURSSVC"] <- "CURRENTEXPEND_SUPPORTSERVICES_TOTAL"
  names(df)[names(df) == "E17"] <- "CURRENTEXPEND_SUPPORTSERVICES_PUPILS"
  names(df)[names(df) == "E07"] <- "CURRENTEXPEND_SUPPORTSERVICES_INSTRUCTIONALSTAFF"
  names(df)[names(df) == "E08"] <- "CURRENTEXPEND_SUPPORTSERVICES_GENERALADMIN"
  names(df)[names(df) == "E09"] <- "CURRENTEXPEND_SUPPORTSERVICES_SCHOOLADMIN"
  names(df)[names(df) == "V40"] <- "CURRENTEXPEND_SUPPORTSERVICES_OP.MAINTENANCEOFPLANT"
  names(df)[names(df) == "V45"] <- "CURRENTEXPEND_SUPPORTSERVICES_STUDENTTRANSPORTATION"
  names(df)[names(df) == "V90"] <- "CURRENTEXPEND_SUPPORTSERVICES_BUSINESS.CENTRAL.OTHER"
  names(df)[names(df) == "V85"] <- "CURRENTEXPEND_SUPPORTSERVICES_NONSPECIFIED"
  names(df)[names(df) == "TCUROTH"] <- "CURRENTEXPEND_OTHERELEMSECOND_TOTAL"
  names(df)[names(df) == "E11"] <- "CURRENTEXPEND_FOODSERVICES"
  names(df)[names(df) == "V60"] <- "CURRENTEXPEND_ENTERPRISEOPS"
  names(df)[names(df) == "V65"] <- "CURRENTEXPEND_OTHER"
  names(df)[names(df) == "TNONELSE"] <- "NONELEMSECONDEXPEND_TOTAL"
  names(df)[names(df) == "V70"] <- "NONELEMSECONDEXPEND_COMMUNITYSERVICES"
  names(df)[names(df) == "V75"] <- "NONELEMSECONDEXPEND_ADULTED"
  names(df)[names(df) == "V80"] <- "NONELEMSECONDEXPEND_OTHER"
  names(df)[names(df) == "TCAPOUT"] <- "CAPITALOUTLAY_TOTAL"
  names(df)[names(df) == "F12"] <- "CAPITALOUTLAY_CONSTRUCTION"
  names(df)[names(df) == "G15"] <- "CAPITALOUTLAY_LAND.EXISTINGSTRUCTURES"
  names(df)[names(df) == "K09"] <- "CAPITALOUTLAY_INSTRUCTIONALEQUIPMENT"
  names(df)[names(df) == "K10"] <- "CAPITALOUTLAY_OTHEREQUIPMENT"
  names(df)[names(df) == "K11"] <- "CAPITALOUTLAY_NONSPECIFEQUIPMENT"
  names(df)[names(df) == "L12"] <- "PAYMENTS_TOSTATEGOV"
  names(df)[names(df) == "M12"] <- "PAYMENTS_TOLOCALGOV"
  names(df)[names(df) == "Q11"] <- "PAYMENTS_TOOTHERSCHOOLSYSTEMS"
  names(df)[names(df) == "I86"] <- "INTERESTONDEBT"
  names(df)[names(df) == "Z32"] <- "SALARIES_TOTAL"
  names(df)[names(df) == "Z33"] <- "SALARIES_INSTRUCTION"
  names(df)[names(df) == "Z35"] <- "SALARIES_TEACHER_REGED"
  names(df)[names(df) == "Z36"] <- "SALARIES_TEACHER_SPED"
  names(df)[names(df) == "Z37"] <- "SALARIES_TEACHER_VOCATIONALED"
  names(df)[names(df) == "Z38"] <- "SALARIES_TEACHER_OTHERED"
  names(df)[names(df) == "V11"] <- "SALARIES_SUPPORTSERVICES_PUPILS"
  names(df)[names(df) == "V13"] <- "SALARIES_SUPPORTSERVICES_INSTRUCTIONALSTAFF"
  names(df)[names(df) == "V15"] <- "SALARIES_SUPPORTSERVICES_GENERALADMIN"
  names(df)[names(df) == "V17"] <- "SALARIES_SUPPORTSERVICES_SCHOOLADMIN"
  names(df)[names(df) == "V21"] <- "SALARIES_SUPPORTSERVICES_OP.MAINTENANCEOFPLANT"
  names(df)[names(df) == "V23"] <- "SALARIES_SUPPORTSERVICES_STUDTRANSPORTATION"
  names(df)[names(df) == "V37"] <- "SALARIES_SUPPORTSERVICES_BUSINESS.CENTRAL_OTHERS"
  names(df)[names(df) == "V29"] <- "SALARIES_FOODSERVICES"
  names(df)[names(df) == "Z34"] <- "EMPBENEFITS_TOTAL"
  names(df)[names(df) == "V10"] <- "EMPBENEFITS_INSTRUCTION"
  names(df)[names(df) == "V12"] <- "EMPBENEFITS_SUPPORTSERVICES_PUPILS"
  names(df)[names(df) == "V14"] <- "EMPBENEFITS_SUPPORTSERVICES_INSTRUCTIONALSTAFF"
  names(df)[names(df) == "V16"] <- "EMPBENEFITS_SUPPORTSERVICES_BUSINESS.CENTRAL_OTHERS"
  names(df)[names(df) == "V18"] <- "EMPBENEFITS_FOODSERVICES"
  names(df)[names(df) == "V22"] <- "EMPBENEFITS_SUPPORTSERVICES_GENERALADMIN"
  names(df)[names(df) == "V24"] <- "EMPBENEFITS_SUPPORTSERVICES_SCHOOLADMIN"
  names(df)[names(df) == "V38"] <- "EMPBENEFITS_SUPPORTSERVICES_OP.MAINTENANCEOFPLANT"
  names(df)[names(df) == "V30"] <- "EMPBENEFITS_SUPPORTSERVICES_STUDTRANSPORTATION"
  names(df)[names(df) == "V32"] <- "EMPBENEFITS_ENTERPRISEOPS"
  names(df)[names(df) == "V93"] <- "TEXTBOOKS"
  names(df)[names(df) == "X_19H"] <- "LONGTERMDEBT_OUTSTANDINGATBEGOFFISCALYR"
  names(df)[names(df) == "X_21F"] <- "LONGTERMDEBT_ISSUEDDURINGFISCALYR"
  names(df)[names(df) == "X_31F"] <- "LONGETERMDEBT_RETIREDDURINGFISCALYR"
  names(df)[names(df) == "X_41F"] <- "LONGETERMDEBT_OUTSTANDINGATENDOFFISCALYR"
  names(df)[names(df) == "X_61V"] <- "SHORTTERMDEBT_OUSTANDINGATBEGOFFISCALYR"
  names(df)[names(df) == "X_66V"] <- "SHORTTERMDEBT_OUSTANDINGATENDOFFISCALYR"
  names(df)[names(df) == "W01"] <- "ASSETS_SINKINGFUND"
  names(df)[names(df) == "W31"] <- "ASSETS_BONDFUND"
  names(df)[names(df) == "W61"] <- "ASSETS_OTHERFUNDS"
  names(df)[names(df) == "HR1"] <- "ARRA_REV_TITLEI"
  names(df)[names(df) == "HE1"] <- "ARRA_CURRENTEXP"
  names(df)[names(df) == "HE2"] <- "ARRA_CAPITALOUTLAYEXP"
  names(df)[names(df) == "C18"] <- "FEDREV_STATE_TITLEVPTA"
  # names(df)[names(df) == "FIPSCO"] <- "FIPSCO" 
  # names(df)[names(df) == "CMSA"] <- "CMSA" 
  # names(df)[names(df) == "AGCHRT"] <- "AGCHRT" 
  # names(df)[names(df) == "CONUM"] <- "CONUM" 
  # names(df)[names(df) == "CSA"] <- "CSA" 
  # names(df)[names(df) == "CBSA"] <- "CBSA" 
  names(df)[names(df) == "V35"] <- "CURRENTEXPEND_SUPORTSERVICES_BUSINESS" 
  names(df)[names(df) == "V50"] <- "CURRENTEXPEND_SUPPORTSERVICES_CENTRAL"
  names(df)[names(df) == "V55"] <- "CURRENTEXPEND_SUPPORTSERVICES_OTHER"
  names(df)[names(df) == "V19"] <- "SALARIES_SUPPORTSERVICES_BUSINESS" 
  names(df)[names(df) == "V25"] <- "SALARIES_SUPPORTSERVICES_CENTRAL"
  names(df)[names(df) == "V27"] <- "SALARIES_SUPPORTSERVICES_OTHER"
  names(df)[names(df) == "V20"] <- "EMPBENEFITS_SUPPORTSERVICES_BUSINESS"
  names(df)[names(df) == "V26"] <- "EMPBENEFITS_SUPPORTSERVICES_CENTRAL"
  names(df)[names(df) == "V28"] <- "EMPBENEFITS_SUPPORTSERVICES_OTHER"
  return(df)
}

# reorder the columns
reorder_col <- function(df) {
  require(data.table)
  
  order <- c("LEAID", "FIPST", "NAME", "YEAR", "FALL_MEMBERSHIP",
             "REV_TOTAL",
             "FEDREV_TOTAL", "FEDREV_STATE_TITLEI", "FEDREV_STATE_IDEA",  "FEDREV_STATE_MATHSCIENCE.TEACHERQUALITY", "FEDREV_STATE_SAFE.DRUGFREE",
             "FEDREV_STATE_VOCATIONAL.TECHED", "FEDREV_STATE_BILINGUALED", "FEDREV_STATE_OTHER", "FEDREV_STATE_CHILDNUTRITIONACT", "FEDREV_STATE_TITLEVPTA",  
             "FEDREV_DIRECT_IMPACTAID", "FEDREV_DIRECT_INDIANED", "FEDREV_DIRECT_OTHERTOTALSTATEREV", "FEDREV_NONSPECIFIED",
             "STATEREV_TOTAL", "STATEREV_GENFORMULA.ASSISTANCE", "STATEREV_STAFFIMPROV_PROGRAMS", "STATEREV_SPED_PROGRAMS", 
             "STATEREV_COMPENSATORY.BASIC.SKILLSPROGRAM","STATEREV_BILINGUALED", "STATEREV_GIFTED.TALENTED_PROGRAMS", "STATEREV_VOCATIONALED_PROGRAMS", 
             "STATEREV_SCHOOLLUNCH", "STATEREV_CAPITALOUTLAY.DEBTSERVICES", "STATEREV_TRANSPORTATION",
             "STATEREV_OTHER", "STATEREV_NONSPECIFIED", "STATEREV_ONBEHALF_EMPLOYEE.BENEFITS", "STATEREV_ONBEHALF_NOTEMPLOYEE.BENEFITS", 
             "LOCALREV_TOTAL", "LOCALREV_PARENTGOVCONRIBUTIONS", "LOCALREV_PROPERTY_TAXES", "LOCALREV_GENERALSALES_TAXES", "LOCALREV_PUBLICUTILITY_TAXES",
             "LOCALREV_INDIVIDUAL.CORPORATEINCOME_TAXES", "LOCALREV_ALLOTHER_TAXES", "LOCALREV_FROMOTHERSCHOOLSYSTEMS", "LOCALREV_FROMCITIES.COUNTIES", 
             "LOCALREV_TUITIONFEESFROMPUPILS.PARENTS", "LOCALREV_TRANSPORTATIONFEESFROMPUPILS.PARENTS", "LOCALREV_SCHOOLLUNCH", "LOCALREV_TEXTBOXSALES.RENTALS", 
             "LOCALREV_DISTRICTACTIVITY.RECEIPTS", "LOCALREV_STUDENTFEES.NONSPECIFIED", "LOCALREV_OTEHRSALES.SERVICES", "LOCALREV_RENTS.ROYALTIES", "LOCALREV_SALEOFPROPERTY", 
             "LOCALREV_INTERESTEARNINGS", "LOCALREV_FINES.FORFEITS", "LOCALREV_PRIVATECONTRIBUTIONS", "LOCALREV_MISC", "LOCALREV_NCES_CENSUSBUREAUSTATEREV", 
             "CURRENTEXPEND_TOTAL", "CURRENTEXPEND_ELEMSECONDEXPEND_TOTAL", "CURRENTEXPEND_INSTRUCTION_TOTAL",
             "CURRENTEXPEND_INSTRUCTION", "CURRENTEXPEND_SUPPORTSERVICES_TOTAL", 
             "CURRENTEXPEND_SUPPORTSERVICES_PUPILS", "CURRENTEXPEND_SUPPORTSERVICES_INSTRUCTIONALSTAFF", "CURRENTEXPEND_SUPPORTSERVICES_GENERALADMIN", 
             "CURRENTEXPEND_SUPPORTSERVICES_SCHOOLADMIN", "CURRENTEXPEND_SUPPORTSERVICES_OP.MAINTENANCEOFPLANT", 
             "CURRENTEXPEND_SUPPORTSERVICES_STUDENTTRANSPORTATION", "CURRENTEXPEND_SUPPORTSERVICES_BUSINESS.CENTRAL.OTHER", 
             "CURRENTEXPEND_SUPORTSERVICES_BUSINESS", "CURRENTEXPEND_SUPPORTSERVICES_CENTRAL", "CURRENTEXPEND_SUPPORTSERVICES_OTHER", 
             "CURRENTEXPEND_SUPPORTSERVICES_NONSPECIFIED", "CURRENTEXPEND_OTHERELEMSECOND_TOTAL", "CURRENTEXPEND_FOODSERVICES", "CURRENTEXPEND_ENTERPRISEOPS",
             "CURRENTEXPEND_OTHER", 
             "NONELEMSECONDEXPEND_TOTAL", "NONELEMSECONDEXPEND_COMMUNITYSERVICES", "NONELEMSECONDEXPEND_ADULTED", "NONELEMSECONDEXPEND_OTHER", 
             "CAPITALOUTLAY_TOTAL", "CAPITALOUTLAY_CONSTRUCTION", "CAPITALOUTLAY_LAND.EXISTINGSTRUCTURES", "CAPITALOUTLAY_INSTRUCTIONALEQUIPMENT",
             "CAPITALOUTLAY_OTHEREQUIPMENT", "CAPITALOUTLAY_NONSPECIFEQUIPMENT", 
             "PAYMENTS_TOSTATEGOV", "PAYMENTS_TOLOCALGOV", "PAYMENTS_TOPRIVATESCH", "PAYMENTS_TOCHARTERSCH", "PAYMENTS_TOOTHERSCHOOLSYSTEMS", "INTERESTONDEBT",
             "SALARIES_TOTAL", "SALARIES_INSTRUCTION", "SALARIES_TEACHER_REGED", "SALARIES_TEACHER_SPED", "SALARIES_TEACHER_VOCATIONALED", 
             "SALARIES_TEACHER_OTHERED", "SALARIES_SUPPORTSERVICES_PUPILS", "SALARIES_SUPPORTSERVICES_INSTRUCTIONALSTAFF", 
             "SALARIES_SUPPORTSERVICES_GENERALADMIN", "SALARIES_SUPPORTSERVICES_SCHOOLADMIN", "SALARIES_SUPPORTSERVICES_OP.MAINTENANCEOFPLANT", 
             "SALARIES_SUPPORTSERVICES_STUDTRANSPORTATION", "SALARIES_SUPPORTSERVICES_BUSINESS.CENTRAL_OTHERS", "SALARIES_SUPPORTSERVICES_BUSINESS",
             "SALARIES_SUPPORTSERVICES_CENTRAL", "SALARIES_SUPPORTSERVICES_OTHER", "SALARIES_FOODSERVICES", 
             "EMPBENEFITS_TOTAL", "EMPBENEFITS_INSTRUCTION", "EMPBENEFITS_SUPPORTSERVICES_PUPILS", "EMPBENEFITS_SUPPORTSERVICES_INSTRUCTIONALSTAFF",
             "EMPBENEFITS_SUPPORTSERVICES_BUSINESS.CENTRAL_OTHERS", "EMPBENEFITS_SUPPORTSERVICES_BUSINESS", "EMPBENEFITS_SUPPORTSERVICES_CENTRAL", 
             "EMPBENEFITS_SUPPORTSERVICES_OTHER", "EMPBENEFITS_FOODSERVICES", "EMPBENEFITS_SUPPORTSERVICES_GENERALADMIN", 
             "EMPBENEFITS_SUPPORTSERVICES_SCHOOLADMIN", "EMPBENEFITS_SUPPORTSERVICES_OP.MAINTENANCEOFPLANT", "EMPBENEFITS_SUPPORTSERVICES_STUDTRANSPORTATION",
             "EMPBENEFITS_ENTERPRISEOPS", 
             "TEXTBOOKS",
             "LONGTERMDEBT_OUTSTANDINGATBEGOFFISCALYR", "LONGTERMDEBT_ISSUEDDURINGFISCALYR", "LONGETERMDEBT_RETIREDDURINGFISCALYR", "LONGETERMDEBT_OUTSTANDINGATENDOFFISCALYR",
             "SHORTTERMDEBT_OUSTANDINGATBEGOFFISCALYR", "SHORTTERMDEBT_OUSTANDINGATENDOFFISCALYR", 
             "ASSETS_SINKINGFUND", "ASSETS_BONDFUND", "ASSETS_OTHERFUNDS", 
             "ARRA_REV_TITLEI", "ARRA_CURRENTEXP", "ARRA_CAPITALOUTLAYEXP"
  )
  df <- setcolorder(df, order)
  
  return(df)
}